### ISSUE TITLE
ImportError: cannot import name 'write_evolution_logs'

### ISSUE THREAD

**Issue by xFFFFF** [Gab0/japonicus#101]
```
python3.6 japonicus.py -b --strat neuralnet2
	GEKKO
     ██╗ █████╗ ██████╗  ██████╗ ███╗   ██╗██╗ ██████╗██╗   ██╗███████╗
     ██║██╔══██╗██╔══██╗██╔═══██╗████╗  ██║██║██╔════╝██║   ██║██╔════╝
     ██║███████║██████╔╝██║   ██║██╔██╗ ██║██║██║     ██║   ██║███████╗
██   ██║██╔══██║██╔═══╝ ██║   ██║██║╚██╗██║██║██║     ██║   ██║╚════██║
╚█████╔╝██║  ██║██║     ╚██████╔╝██║ ╚████║██║╚██████╗╚██████╔╝███████║
 ╚════╝ ╚═╝  ╚═╝╚═╝      ╚═════╝ ╚═╝  ╚═══╝╚═╝ ╚═════╝ ╚═════╝ ╚══════╝
								v0.53

The profits reported here are the profit beyond market price change;
	i.e. shown profit =  <backtest profit> - <market profit in evaluated candlestick period>;
Traceback (most recent call last):
  File "japonicus.py", line 114, in <module>
    import evolution_bayes
  File "/home/f/!skrypty/gekko/backtestbnb/japonicus/evolution_bayes.py", line 19, in <module>
    from promoterz.statistics import write_evolution_logs
ImportError: cannot import name 'write_evolution_logs'

```

**Comment by Gab0** [comment]
Thats an error on bayes_evolution... Fixing on next push.
Thanks!
