### ISSUE TITLE
Japonicus crash

### ISSUE THREAD

**Issue by xFFFFF** [Gab0/japonicus#116]
```
evolution candlestick dataset 2017-11-11 08:25:00 to 2018-04-05 22:32:00
BCC/BNB @binance



evaluation candlestick dataset 2017-11-06 06:25:00 to 2018-04-05 14:25:00
VEN/BNB @binance

	======  EPOCH 0/800  ======
Locale1
first unevaluated: 5
0 individues removed due to equality
[5]
Traceback (most recent call last):
  File "japonicus.py", line 154, in <module>
    launchJaponicus()
  File "japonicus.py", line 139, in launchJaponicus
    TargetParameters, GenerationMethod, EvaluationMode, web=web_server
  File "/home/f/gekko/japonicus/evolution_generations.py", line 170, in gekko_generations
    World.runEPOCH()
  File "/home/f/gekko/japonicus/promoterz/sequence/parallel_world.py", line 13, in world_EPOCH
    LOCALE.run()
  File "/home/f/gekko/japonicus/promoterz/locale.py", line 39, in run
    self.loop(self.World, self)
  File "/home/f/gekko/japonicus/promoterz/sequence/standard_loop.py", line 34, in standard_loop
    locale
  File "/home/f/gekko/japonicus/promoterz/evaluationPool.py", line 84, in evaluatePopulation
    print(showIndividue(fit))
  File "/home/f/gekko/japonicus/promoterz/evaluationPool.py", line 10, in <lambda>
    evaldata[0][0], evaldata[0][1], evaldata[1]
KeyError: 0

```

**Comment by xFFFFF** [comment]
I never wait for all epochs :) I will back to older version and Im waiting for fix.
