### ISSUE TITLE
2 errors always occur when running -g (KeyError: 'dateRange')

### ISSUE THREAD

**Issue by mo2bel** [Gab0/japonicus#126]
I get the below errors every time I run -g. I got them 4 times till now, once at epoch 80, once at epoch 180, once at epoch 280 and the last time at epoch 380.

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/indexes/base.py", line 2442, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc (pandas/_libs/index.c:5280)
  File "pandas/_libs/index.pyx", line 154, in pandas._libs.index.IndexEngine.get_loc (pandas/_libs/index.c:5126)
  File "pandas/_libs/hashtable_class_helper.pxi", line 1210, in pandas._libs.hashtable.PyObjectHashTable.get_item (pandas/_libs/hashtable.c:20523)
  File "pandas/_libs/hashtable_class_helper.pxi", line 1218, in pandas._libs.hashtable.PyObjectHashTable.get_item (pandas/_libs/hashtable.c:20477)
KeyError: 'dateRange'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "japonicus.py", line 154, in <module>
    launchJaponicus()
  File "japonicus.py", line 139, in launchJaponicus
    TargetParameters, GenerationMethod, EvaluationMode, web=web_server
  File "/home/moe/gekko/japonicus/evolution_generations.py", line 170, in gekko_generations
    World.runEPOCH()
  File "/home/moe/gekko/japonicus/promoterz/sequence/parallel_world.py", line 21, in world_EPOCH
    World.web.update_graph(LOCALE.name, LOCALE.EvolutionStatistics),
  File "/home/moe/gekko/japonicus/web.py", line 45, in update_graph
    for W in range(len(df['dateRange'])):
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py", line 1964, in __getitem__
    return self._getitem_column(key)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py", line 1971, in _getitem_column
    return self._get_item_cache(key)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/generic.py", line 1645, in _get_item_cache
    values = self._data.get(item)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/internals.py", line 3590, in get
    loc = self.items.get_loc(item)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/indexes/base.py", line 2444, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc (pandas/_libs/index.c:5280)
  File "pandas/_libs/index.pyx", line 154, in pandas._libs.index.IndexEngine.get_loc (pandas/_libs/index.c:5126)
  File "pandas/_libs/hashtable_class_helper.pxi", line 1210, in pandas._libs.hashtable.PyObjectHashTable.get_item (pandas/_libs/hashtable.c:20523)
  File "pandas/_libs/hashtable_class_helper.pxi", line 1218, in pandas._libs.hashtable.PyObjectHashTable.get_item (pandas/_libs/hashtable.c:20477)
KeyError: 'dateRange'

**Comment by Gab0** [comment]
Hey, that error is for web interface only, it doesn't interrupt the runs, right? I'm looking into this, seems like a japonicus statistics -> web interface integration problem... aparently has no errors, but these things are just chaotic.  cheers!

**Comment by mo2bel** [comment]
Actually, the runs stopped every single time. I hard reset the HEAD and run a git pull, that seems to have solved the issue somehow!
