### ISSUE TITLE
 No module named 'js2py'

### ISSUE THREAD

**Issue by xaviermiss** [Gab0/japonicus#128]
Hi,

No way to get japonicus run.
I always get this error even if js2py is installed:

$ python3.6 japonicus.py -g --repeat 10 --skeleton ontrend -w
Traceback (most recent call last):
  File "japonicus.py", line 14, in <module>
    from Settings import getSettings
  File "/home/xavier/japonicus/Settings.py", line 3, in <module>
    import js2py
ModuleNotFoundError: No module named 'js2py'

If I try to reinstall js2py, I obtain:
$ sudo pip install js2py
Requirement already satisfied: js2py in /usr/local/lib/python2.7/dist-packages (0.50)

I can see that it is in the version 2.7 folder of python.
The error comes perhaps from thet but I do not know how to resolve it.

Can someone help me ?

Thanks 
Xavier

**Comment by Gab0** [comment]
Hey, use `sudo pip3 install js2py`
or better, `sudo pip3 install -r requirements.txt` at japn folder, which will install everything.
