### ISSUE TITLE
Baysian OPtimization : AttributeError: module 'resultInterface' has no attribute 'parametersToTOML'

### ISSUE THREAD

**Issue by hugokoopmans** [Gab0/japonicus#130]
Hi,

python japonicus.py -b --strat RSI_BULL_BEAR_ADX
runs
step 1 ok
step 2 ok
but on step 3

Traceback (most recent call last):
  File "japonicus.py", line 171, in <module>
    launchJaponicus(parser)
  File "japonicus.py", line 163, in launchJaponicus
    evolution_bayes.gekko_bayesian(Strategy)
  File "/home/hugo/git/gekko/japonicus/evolution_bayes.py", line 156, in gekko_bayesian
    print(resultInterface.parametersToTOML(resultjson))
AttributeError: module 'resultInterface' has no attribute 'parametersToTOML'

Any thoughts?

thx

**Comment by Gab0** [comment]
Fixed on develop branch ;}
