### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'dict' and 'str'

### ISSUE THREAD

**Issue by nimasTT** [Gab0/japonicus#153]
I am getting the Error message on win10 bash, when i am trying:
python3.6 japonicus.py -b --repeat 7 --strat RSI_BULL_BEAR

`The profits reported here depends on backtest interpreter function;
        interpreter v3:
if <backtest profit> > 0: <shown profit> = <backtest profit> - <market profit>
else <shown profit> = <backtest profit>

found gekko @ http://localhost:3000
unable to locate http://gekko:3000
Traceback (most recent call last):
  File "japonicus.py", line 198, in <module>
    launchJaponicus(settings, options)
  File "japonicus.py", line 186, in launchJaponicus
    import evolution_bayes
  File "/mnt/c/Users/Nima/japonicus/evolution_bayes.py", line 42, in <module>
    watch, DatasetRange = evaluation.gekko.dataset.selectCandlestickData(watch)
  File "/mnt/c/Users/Nima/japonicus/evaluation/gekko/dataset.py", line 15, in selectCandlestickData
    DataSetPack = getAllScanset(GekkoURL)
  File "/mnt/c/Users/Nima/japonicus/evaluation/gekko/dataset.py", line 9, in getAllScanset
    URL = GekkoURL + '/api/scansets'
TypeError: unsupported operand type(s) for +: 'dict' and 'str'`

**Comment by Gab0** [comment]
Oh yeah, that seems to be a bug on bayesian methods. `-b` is surely unstable because I never use it myself XD, might update a fix later.

**Comment by nimasTT** [comment]
I don't use it either ^_^ By using genetic, I got the error, that my timerage is set bigger than my dataset (my dataset range was 30 Days long and i just set the rage to 10 days.)
because the only option for changing daterange was in the bayesian options, i tried to use -b option.
