### ISSUE TITLE
Requirements.txt Install Error

### ISSUE THREAD

**Issue by BradT7** [Gab0/japonicus#155]
```Collecting tulipy==0.2 (from -r requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/52/64/40567aebd73c8778b24e316fffbb1aae1b59c2c7d2e52841f40cb7a341ab/tulipy-0.2.tar.gz (94kB)
    100% |████████████████████████████████| 102kB 2.3MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-aq1t4vqq/tulipy/setup.py", line 4, in <module>
        import numpy as np
    ModuleNotFoundError: No module named 'numpy'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-aq1t4vqq/tulipy/
```

Running latest Mint 19, tried pip18 and pip9.0.1

Any assistance would be great! trying to get this to run on latest gekko 0.6.6

**Comment by nixlong** [comment]
it should be lacked of the numpy module ,just install it like this:

> $sudo python3.6 -m pip install numpy  

//if ur python version is python3.6

**Comment by IAMtheIAM** [comment]
That worked, but why doesn't `numpy` get installed from `requirements.txt`?
