### ISSUE TITLE
i get a bool error 

### ISSUE THREAD

**Issue by zhangarejiu** [Gab0/japonicus#162]
when i run ,i got bool error,someone can help,thank you
he profits reported here depends on backtest interpreter function; 
        interpreter v3: 
if <backtest profit> > 0: <shown profit> = <backtest profit> - <market profit> 
else <shown profit> = <backtest profit> 

found gekko @ http://localhost:3000
found gekko @ http://gekko:3000
Error: config failure
Expecting value: line 1 column 1 (char 0)
http://localhost:3000/api/scansets
{}
Traceback (most recent call last):
  File "japonicus-run", line 10, in <module>
    japonicus.launchJaponicus(settings, options)
  File "/root/gekko/japonicus/japonicus/japonicus.py", line 181, in launchJaponicus
    EvaluationMode, settings, options, web=web_server
  File "/root/gekko/japonicus/japonicus/evolution_generations.py", line 134, in gekko_generations
    evolutionDatasets, evaluationDatasets = grabDatasets(datasetconf, globalconf.GekkoURLs[0])
  File "/root/gekko/japonicus/japonicus/evolution_generations.py", line 76, in grabDatasets
    exchange_source=datasetconf.__dict__[evolutionDatasetName]
  File "/root/gekko/japonicus/evaluation/gekko/dataset.py", line 14, in selectCandlestickData
    DataSetPack = getAllScanset(GekkoURL)
  File "/root/gekko/japonicus/evaluation/gekko/dataset.py", line 10, in getAllScanset
    return RESP['datasets']
TypeError: 'bool' object is not subscriptable

**Comment by nixlong** [comment]
no asset data in your history database?

**Comment by Gab0** [comment]
Hey @zhangarejiu , yeah it seems there is no asset data in your history database as pointed by nixlong... can you check it?
