### ISSUE TITLE
ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by AJ-gohan** [Gab0/japonicus#164]
hi, I'm trying to run GA on Neuralnetwork but i get the following error, any idea on how to solve this?
$python3 japonicus-run -g --strat NNv2

Traceback (most recent call last):
  File "japonicus-run", line 10, in <module>
    japonicus.launchJaponicus(settings, options)
  File "/home/Downloads/binance/Gekko-GA/japonicus/japonicus/japonicus.py", line 181, in launchJaponicus
    EvaluationMode, settings, options, web=web_server
  File "/home/Downloads/binance/Gekko-GA/japonicus/japonicus/evolution_generations.py", line 134, in gekko_generations
    evolutionDatasets, evaluationDatasets = grabDatasets(datasetconf, globalconf.GekkoURLs[0])
  File "/home/Downloads/binance/Gekko-GA/japonicus/japonicus/evolution_generations.py", line 76, in grabDatasets
    exchange_source=datasetconf.__dict__[evolutionDatasetName]
  File "/home/Downloads/binance/Gekko-GA/japonicus/evaluation/gekko/dataset.py", line 47, in selectCandlestickData
    LONGEST = range_spans.index(max(range_spans))
ValueError: max() arg is an empty sequence

**Comment by nixlong** [comment]
>  ValueError: max() arg is an empty sequence

=====================

`# OPERATE FOUND SCANSETS;
 44     for EXCHANGE in scanset:
 45         ranges = EXCHANGE['ranges']
 46         range_spans = [x['to'] - x['from'] for x in ranges]
 47         LONGEST = range_spans.index(max(range_spans))`

refer to the api:  https://gekko.wizb.it/docs/internals/server_api.html#POST-api-scansets

no asset data  in your history database?

**Comment by AJ-gohan** [comment]
oh, I deleted the previously made db-shm and db-wal databases and it solved the problem
thank you for the hint.
