### ISSUE TITLE
Error : local variable 'backtestResult' referenced before assignment

### ISSUE THREAD

**Issue by nimasTT** [Gab0/japonicus#170]
i am getting this Error after a while: 
`Traceback (most recent call last):
  File "japonicus-run", line 10, in <module>
    japonicus.launchJaponicus(settings, options)
  File "/mnt/c/Users/Nima/japonicus/japonicus/japonicus.py", line 181, in launchJaponicus
    EvaluationMode, settings, options, web=web_server
  File "/mnt/c/Users/Nima/japonicus/japonicus/evolution_generations.py", line 259, in gekko_generations
    promoterz.evaluationBreak.showResults(World)
  File "/mnt/c/Users/Nima/japonicus/promoterz/evaluationBreak.py", line 119, in showResults
    currentSessionBreakResults.append((backtestResult['relativeProfit'], TOMLSettings))UnboundLocalError: local variable 'backtestResult' referenced before assignment`

Could it caused by running too many parallel Backtest?

**Comment by nimasTT** [comment]
I though it could be maybe because of a concurrency problem. 
I have tried more runs with default options (6 parallel Backtests) on an 10 years old i5 Laptop. but i get the Failure each time after EPOCH 50. 
I tried it also with 3 parallel Backtests. I get the same message.

**Comment by Fauchr** [comment]
I think it's not a dependency problem.

Some rows before @nimasTT  log are interesting, because I have the same issue:

`Relative profit on evolution dataset: 445.165
Current parameters are viable.
**Evaluation dataset is disabled.**
~~~~~~~~~~~~~~~~~~
 445.165 final profit ~~~~
 -- Settings for Gekko config.js --
{
  "ADX": 3.432,
`

If there is no "evaluation dataset", the var backtestresult will not be assigned at row 100 before it is referenced in row 121 (current version)

**Comment by Gab0** [comment]
I think this is it... I never tested myself without evaluation dataset XD.
Nice catch, fix is going online soon.
