### ISSUE TITLE
pip install Exception

### ISSUE THREAD

**Issue by Cappuccino90** [Gab0/japonicus#46]
Hi, trying to get your project to run. Failed at the pip install part. Do I need a specific python version?

`root@raspberrypi:/home/pi/Downloads/gekkoJaponicus-master# sudo pip install -r requirements.txt
Collecting deap==1.0.2.post2 (from -r requirements.txt (line 1))
  Downloading deap-1.0.2.post2.tar.gz (852kB)
    100% |################################| 860kB 286kB/s 
  Requested deap==1.0.2.post2 from https://pypi.python.org/packages/5b/d7/a49d3dd7aa8cbaf2b1ac8f4d6495824c886fea8b3dac4a73dc4df94cad76/deap-1.0.2.post2.tar.gz#md5=ccf5ed7562e4d6236c9416e3b5a9d941 (from -r requirements.txt (line 1)), but installing version None
Collecting requests==2.14.2 (from -r requirements.txt (line 2))
  Downloading requests-2.14.2-py2.py3-none-any.whl (560kB)
    100% |################################| 563kB 412kB/s 
Requirement already satisfied: numpy==1.12.1 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 3))
Collecting js2py==0.50 (from -r requirements.txt (line 4))
  Downloading Js2Py-0.50.tar.gz (552kB)
    100% |################################| 552kB 402kB/s 
Collecting bayesian-optimization==0.4.0 (from -r requirements.txt (line 5))
  Downloading bayesian-optimization-0.4.0.tar.gz
Collecting matplotlib==1.5.3 (from -r requirements.txt (line 6))
  Downloading matplotlib-1.5.3.tar.gz (51.6MB)
    99% |############################### | 51.6MB 4.3MB/s eta 0:00:01Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 821, in unpack_url
    hashes=hashes
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 659, in unpack_http_url
    hashes)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 882, in _download_http_url
    _download_url(resp, link, content_file, hashes)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 603, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "/usr/lib/python2.7/dist-packages/pip/utils/hashes.py", line 46, in check_against_chunks
    for chunk in chunks:
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 571, in written_chunks
    for chunk in chunks:
  File "/usr/lib/python2.7/dist-packages/pip/utils/ui.py", line 139, in iter
    for x in it:
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 560, in resp_read
    decode_content=False):
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/response.py", line 432, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/response.py", line 380, in read
    data = self._fp.read(amt)
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/filewrapper.py", line 63, in read
    self._close()
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/filewrapper.py", line 50, in _close
    self.__callback(self.__buf.getvalue())
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/controller.py", line 275, in cache_response
    self.serializer.dumps(request, response, body=body),
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/serialize.py", line 87, in dumps
    ).encode("utf8"),
MemoryError
`

**Comment by adamrjd** [comment]
Have you checked how much memory is left on the raspberry pi that you're installing onto?

**Comment by Cappuccino90** [comment]
@adamrjd Yeah the memory was running full. Solved it with zRAM.
But now there is a diffrent Exception. Apparently wrong operands got used. Sounds like a python version error to me. My python3 version is **3.5.3**. Updating to 3.6.0 on my raspberry pi is not easy. Been trying it for the last hour. Do you think upgrading to 3.6.0 is the solution to the new problem?

`  Downloading Flask-Compress-1.4.0.tar.gz
Collecting flask-seasurf (from dash==0.18.3->-r requirements.txt (line 9))
  Downloading Flask-SeaSurf-0.2.2.tar.gz
Collecting pandas (from quantmod->-r requirements.txt (line 13))
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 792, in get_page
    "Cache-Control": "max-age=600",
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 643, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/util/retry.py", line 315, in increment
    total -= 1
TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'
`

**Comment by adamrjd** [comment]
@Cappuccino90 it looks like it's failing to install matplotlib specifically -- just try to install that library separately

`pip install matplotlib`

that lib is kinda big though just fyi. if i'd have been using a pi to do this, i would've installed an anaconda distro of python specific for the pi

**Comment by Gab0** [comment]
Hey @Cappuccino90, I do not work with ARM machines and can't see advantages on running genetic algorithms on such performance limited devices ^^. From my experience on issues shown here, japonicus seems to need python3.6 to run properly. You can still try..
 Your first problem was on matplotlib install as pointed by @adamrjd, second problem was on flask.
 First, make sure you are running pip for your python3: `$sudo pip3 -r requirements.txt`, as those runs seems to be for python2. If still failing, those requirements.txt items below bayesian-optimization are really just for graphical watcher of the evolution, thus optional but japonicus still require them due to bad design XD.
 If you cant manage to install all of em under py3, report here so I can make a patch for jap. to ignore those packages.

**Comment by jk-85** [comment]
I installed python 3.6.

I ended here also. It's a pain in the neck for hours now. Could you simply put out the graphical watcher. I also tried to install it on my Raspberry 3 and really found no solution so far. On my virtual machine with VirtualBox, Xubuntu it installed flawless, but when I try to install it on my Raspberry 3 I really got stuck and finally found out it's the requiredments.txt-part "bayesian-optimization".

sudo pip3 install -r requirements.txt

Here's part of the output:

   Found existing installation: deap 1.0.2
    Uninstalling deap-1.0.2:
      Successfully uninstalled deap-1.0.2
  Running setup.py install for deap ... done
  Running setup.py install for scipy ... error
    Complete output from command /usr/local/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ubo75akw/scipy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-bbunrwoa-record/install-record.txt --single-version-externally-managed --compile:

    Note: if you need reliable uninstall behavior, then install
    with pip instead of using `setup.py install`:

      - pip install .       (from a git repo or downloaded source
                               release)
      - pip install scipy   (last SciPy release on PyPI)


    lapack_opt_info:
    lapack_mkl_info:
      libraries mkl_rt not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/arm-linux-gnueabihf']
      NOT AVAILABLE

    openblas_lapack_info:
      libraries openblas not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/arm-linux-gnueabihf']
      NOT AVAILABLE

    atlas_3_10_threads_info:
    Setting PTATLAS=ATLAS
      libraries tatlas,tatlas not found in /usr/local/lib
      libraries lapack_atlas not found in /usr/local/lib
      libraries tatlas,tatlas not found in /usr/lib
      libraries lapack_atlas not found in /usr/lib
      libraries tatlas,tatlas not found in /usr/lib/arm-linux-gnueabihf
      libraries lapack_atlas not found in /usr/lib/arm-linux-gnueabihf
    <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      NOT AVAILABLE

    atlas_3_10_info:
      libraries satlas,satlas not found in /usr/local/lib
      libraries lapack_atlas not found in /usr/local/lib
      libraries satlas,satlas not found in /usr/lib
      libraries lapack_atlas not found in /usr/lib
      libraries satlas,satlas not found in /usr/lib/arm-linux-gnueabihf
      libraries lapack_atlas not found in /usr/lib/arm-linux-gnueabihf
    <class 'numpy.distutils.system_info.atlas_3_10_info'>
      NOT AVAILABLE

    atlas_threads_info:
    Setting PTATLAS=ATLAS
      libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
      libraries lapack_atlas not found in /usr/local/lib
      libraries ptf77blas,ptcblas,atlas not found in /usr/lib
      libraries lapack_atlas not found in /usr/lib
      libraries ptf77blas,ptcblas,atlas not found in /usr/lib/arm-linux-gnueabihf
      libraries lapack_atlas not found in /usr/lib/arm-linux-gnueabihf
    <class 'numpy.distutils.system_info.atlas_threads_info'>
      NOT AVAILABLE

    atlas_info:
      libraries f77blas,cblas,atlas not found in /usr/local/lib
      libraries lapack_atlas not found in /usr/local/lib
      libraries f77blas,cblas,atlas not found in /usr/lib
      libraries lapack_atlas not found in /usr/lib
      libraries f77blas,cblas,atlas not found in /usr/lib/arm-linux-gnueabihf
      libraries lapack_atlas not found in /usr/lib/arm-linux-gnueabihf
    <class 'numpy.distutils.system_info.atlas_info'>
      NOT AVAILABLE

    /usr/local/lib/python3.6/site-packages/numpy/distutils/system_info.py:572: UserWarning:
        Atlas (http://math-atlas.sourceforge.net/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [atlas]) or by setting
        the ATLAS environment variable.
      self.calc_info()
    lapack_info:
      libraries lapack not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/arm-linux-gnueabihf']
      NOT AVAILABLE

    /usr/local/lib/python3.6/site-packages/numpy/distutils/system_info.py:572: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      self.calc_info()
    lapack_src_info:
      NOT AVAILABLE

    /usr/local/lib/python3.6/site-packages/numpy/distutils/system_info.py:572: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      self.calc_info()
      NOT AVAILABLE

    Running from scipy source directory.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ubo75akw/scipy/setup.py", line 418, in <module>
        setup_package()
      File "/tmp/pip-build-ubo75akw/scipy/setup.py", line 414, in setup_package
        setup(**metadata)
      File "/usr/local/lib/python3.6/site-packages/numpy/distutils/core.py", line 135, in setup
        config = configuration()
      File "/tmp/pip-build-ubo75akw/scipy/setup.py", line 336, in configuration
        config.add_subpackage('scipy')
      File "/usr/local/lib/python3.6/site-packages/numpy/distutils/misc_util.py", line 1001, in add_subpackage
        caller_level = 2)
      File "/usr/local/lib/python3.6/site-packages/numpy/distutils/misc_util.py", line 970, in get_subpackage
        caller_level = caller_level + 1)
      File "/usr/local/lib/python3.6/site-packages/numpy/distutils/misc_util.py", line 907, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy/setup.py", line 15, in configuration
        config.add_subpackage('linalg')
      File "/usr/local/lib/python3.6/site-packages/numpy/distutils/misc_util.py", line 1001, in add_subpackage
        caller_level = 2)
      File "/usr/local/lib/python3.6/site-packages/numpy/distutils/misc_util.py", line 970, in get_subpackage
        caller_level = caller_level + 1)
      File "/usr/local/lib/python3.6/site-packages/numpy/distutils/misc_util.py", line 907, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy/linalg/setup.py", line 19, in configuration
        raise NotFoundError('no lapack/blas resources found')
    numpy.distutils.system_info.NotFoundError: no lapack/blas resources found

    ----------------------------------------
Command "/usr/local/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ubo75akw/scipy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-bbunrwoa-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-ubo75akw/scipy/

**Comment by Gab0** [comment]
@jk-85 So scipy is a pain to install on raspberry... There are some tutorials on it, if doesn't work at all just remove from `requirements.txt`, I think its only used on bayesian optimization.
But hey... why are you guys trying to run genetic algorithms on raspberrys? hehe I can't understand :'(

**Comment by jk-85** [comment]
So, at the end, scipy wasn't the only pain. But yes, I think its better to forget these setup, it's really annoying with a Raspberry and instead focus on my better quad-core machine. Idea was to have that all in a little box that doesn't require much energy, but you're right, these algorithms need better hardware.
