### ISSUE TITLE
Memory Errors on limited memory machines

### ISSUE THREAD

**Issue by b1kjsh** [Gab0/japonicus#49]
```
Locale1
first unevaluated: 30
0 individues removed due to equality
[30]
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 405, in _handle_workers
    pool._maintain_pool()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 246, in _maintain_pool
    self._repopulate_pool()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 239, in _repopulate_pool
    w.start()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 26, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 73, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
```

I started a small $5 droplet on digitalocean to run all this stuff on. However when I run `python3.6 japonicus.py -g -i -k` it'll initialize and then it will fail with the message above. The machine is only limited to about 500MB of memory but the threading needs to be so that it can accommodate it even though it'll run slower.

**Comment by Gab0** [comment]
hello... you can try to change `generations.ParallelBacktests` to a smaller value (1~3) on Settings.py. Maybe you'll  need to run this on a bigger machine.
