### ISSUE TITLE
raise ValueError("empty range for randrange()

### ISSUE THREAD

**Issue by kevinwong1983** [Gab0/japonicus#50]
getting the following error when starting up the application.. Am I setting the configuration wrong?

using candlestick dataset 2017-09-12 00:00:00 to 2017-10-11 23:58:00

Traceback (most recent call last):
  File "japonicus.py", line 95, in <module>
    gekko_generations(TargetParameters, GenerationMethod, EvaluationMode, web=APP)
  File "/Users/kevin/Documents/Workspace/gekkoJaponicus/gekkoJaponicus/evolution_generations.py", line 100, in gekko_generations
    EnvironmentParameters=availableDataRange, web=web)
  File "/Users/kevin/Documents/Workspace/gekkoJaponicus/gekkoJaponicus/promoterz/world.py", line 27, in __init__
    self.generateLocale()
  File "/Users/kevin/Documents/Workspace/gekkoJaponicus/gekkoJaponicus/promoterz/world.py", line 35, in generateLocale
    random.choice(self.loops))
  File "/Users/kevin/Documents/Workspace/gekkoJaponicus/gekkoJaponicus/promoterz/locale.py", line 39, in __init__
    for x in range(World.genconf.NBCandlestickData) ]
  File "/Users/kevin/Documents/Workspace/gekkoJaponicus/gekkoJaponicus/promoterz/locale.py", line 39, in <listcomp>
    for x in range(World.genconf.NBCandlestickData) ]
  File "/Users/kevin/Documents/Workspace/gekkoJaponicus/gekkoJaponicus/promoterz/locale.py", line 36, in <lambda>
    World.EnvironmentParameters, World.genconf.deltaDays)
  File "/Users/kevin/Documents/Workspace/gekkoJaponicus/gekkoJaponicus/promoterz/evaluation/gekko.py", line 291, in getRandomDateRange
    Starting= random.randint(FLms,TLms-deltams)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/random.py", line 221, in randint
    return self.randrange(a, b+1)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/random.py", line 199, in randrange
    raise ValueError("empty range for randrange() (%d,%d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (1505174400,1502582281, -2592119)
127.0.0.1 - - [12/Jan/2018 22:14:42] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [12/Jan/2018 22:14:42] "POST /_dash-update-component HTTP/1.1" 200 -

**Comment by Gab0** [comment]
Hey @kevinwong1983, are u using sqlite3 on gekko database? Aside that it seems you have one very small candle database, on time length, on gekko.. please paste your database info here. cheers!

**Comment by kevinwong1983** [comment]
Hi @Gab0,
I am using the default UI configurations from Gekko.

config.sqlite = {
  path: 'plugins/sqlite',
  version: 0.1,
  dataDirectory: 'history',
  journalMode: require('../isWindows.js') ? 'PERSIST' : 'WAL',
  dependencies: [{
    module: 'sqlite3',
    version: '3.1.4'
  }]
}

The dataset I am using should be one month: using candlestick dataset 2017-09-12 00:00:00 to 2017-10-11 23:58:00

Regards,
Kevin

**Comment by xtebs** [comment]
Same happened to me. I appear that the problem comes from [PROJECT]/promoterz/evaluation/gekko.py file at line 296.
`Starting= random.randint(TLms-deltams,FLms)`

Apaerantly if **TLms-deltams> than FLms**, python random function crashes.
I changed the order in my case, and it worked, but crashed in another problem afterward :D .

So I am not sure if this is the real solution, or just delaying the problem 👍

**Comment by Gab0** [comment]
hey @kevinwong1983, one month is a very small timeframe! Thats the cause of the problem. Standard timeframe is 60 (days), set on generations.deltaDays on Settings.py! You can always lower that setting to fit your data. Of course that would deteriorate the results you get by running this GA.

hello @xtebs, that overflow is caused by the app searching for std 60 days on a small database, isn't? x]

Anyway the program needs a proper warning system to set those things clear for the users, so sorry and thanks for the reports! I'm looking into it.

**Comment by xtebs** [comment]
@Gab0 Your totally right. That is the cause of the problem. please don't "sorry", we are the ones to say "thank you". This is open, and that is honorable. (I hope I can contribute more often)

**Comment by kevinwong1983** [comment]
Thanks Guys!
