### ISSUE TITLE
Custom strategies

### ISSUE THREAD

**Issue by deadheadtn** [Gab0/japonicus#64]
Having everything working with the Standard strategies present in gekko
using the custom strategies i have this issue
just by running this `python3.6 japonicus.py --strat buyatsellatPPO -g`

````
	GEKKO
     ██╗ █████╗ ██████╗  ██████╗ ███╗   ██╗██╗ ██████╗██╗   ██╗███████╗
     ██║██╔══██╗██╔══██╗██╔═══██╗████╗  ██║██║██╔════╝██║   ██║██╔════╝
     ██║███████║██████╔╝██║   ██║██╔██╗ ██║██║██║     ██║   ██║███████╗
██   ██║██╔══██║██╔═══╝ ██║   ██║██║╚██╗██║██║██║     ██║   ██║╚════██║
╚█████╔╝██║  ██║██║     ╚██████╔╝██║ ╚████║██║╚██████╗╚██████╔╝███████║
 ╚════╝ ╚═╝  ╚═╝╚═╝      ╚═════╝ ╚═╝  ╚═══╝╚═╝ ╚═════╝ ╚═════╝ ╚══════╝
								v0.29

The profits reported here are the profit beyond market price change;
	i.e. shown profit =  <backtest profit> - <market profit in evaluated candlestick period>;
Evolving buyatsellatPPO strategy;

evaluated parameters ranges:
buyat                         (1.03, 1.2)
sellat                        (0.92, 0.97)
stop_loss_pct                 (0.87, 0.95)
sellat_up                     (1.01, 1.2)
short                         (6, 18)
long                          (13, 39)
signal                        (1, 18)
thresholds.down               (-0.5, 0.0)
thresholds.up                 (0.0, 0.5)
thresholds.persistence        (2, 10)

using candlestick dataset 2018-01-20 19:24:00 to 2018-01-28 19:23:00

	======  EPOCH 0/400  ======
Locale1
first unevaluated: 30
0 individues removed due to equality
[30]
Error: config failure
http://localhost:3000/api/backtest
{'gekkoConfig': {'debug': True, 'info': True, 'watch': {'exchange': 'binance', 'currency': 'BTC', 'asset': 'ETH'}, 'paperTrader': {'fee': 0.25, 'feeMaker': 0.15, 'feeTaker': 0.25, 'feeUsing': 'maker', 'slippage': 0.05, 'simulationBalance': {'asset': 1, 'currency': 100}, 'reportRoundtrips': True, 'enabled': True}, 'tradingAdvisor': {'enabled': True, 'method': 'buyatsellatPPO', 'candleSize': 15, 'historySize': 10}, 'buyatsellatPPO': {'buyat': 1.0929, 'long': 31.46, 'sellat': 0.9430000000000001, 'sellat_up': 1.1543999999999999, 'short': 17.04, 'signal': 7.800000000000001, 'stop_loss_pct': 0.8932, 'thresholds': {'down': -0.14500000000000002, 'persistence': 7.04, 'up': 0.48}}, 'backtest': {'daterange': {'from': '2018-01-21 05:17:44', 'to': '2018-01-27 05:17:44'}}, 'performanceAnalyzer': {'riskFreeReturn': 2, 'enabled': True}, 'valid': True}, 'data': {'candleProps': ['id', 'start', 'open', 'high', 'low', 'close', 'vwp', 'volume', 'trades'], 'indicatorResults': True, 'report': True, 'roundtrips': False, 'trades': True}}
Error: config failure
http://localhost:3000/api/backtest
{'gekkoConfig': {'debug': True, 'info': True, 'watch': {'exchange': 'binance', 'currency': 'BTC', 'asset': 'ETH'}, 'paperTrader': {'fee': 0.25, 'feeMaker': 0.15, 'feeTaker': 0.25, 'feeUsing': 'maker', 'slippage': 0.05, 'simulationBalance': {'asset': 1, 'currency': 100}, 'reportRoundtrips': True, 'enabled': True}, 'tradingAdvisor': {'enabled': True, 'method': 'buyatsellatPPO', 'candleSize': 15, 'historySize': 10}, 'buyatsellatPPO': {'buyat': 1.1439, 'long': 21.58, 'sellat': 0.9390000000000001, 'sellat_up': 1.1373, 'short': 17.28, 'signal': 7.630000000000001, 'stop_loss_pct': 0.8884, 'thresholds': {'down': -0.22499999999999998, 'persistence': 2.56, 'up': 0.21}}, 'backtest': {'daterange': {'from': '2018-01-21 05:17:44', 'to': '2018-01-27 05:17:44'}}, 'performanceAnalyzer': {'riskFreeReturn': 2, 'enabled': True}, 'valid': True}, 'data': {'candleProps': ['id', 'start', 'open', 'high', 'low', 'close', 'vwp', 'volume', 'trades'], 'indicatorResults': True, 'report': True, 'roundtrips': False, 'trades': True}}
Error: config failure
http://localhost:3000/api/backtest
{'gekkoConfig': {'debug': True, 'info': True, 'watch': {'exchange': 'binance', 'currency': 'BTC', 'asset': 'ETH'}, 'paperTrader': {'fee': 0.25, 'feeMaker': 0.15, 'feeTaker': 0.25, 'feeUsing': 'maker', 'slippage': 0.05, 'simulationBalance': {'asset': 1, 'currency': 100}, 'reportRoundtrips': True, 'enabled': True}, 'tradingAdvisor': {'enabled': True, 'method': 'buyatsellatPPO', 'candleSize': 15, 'historySize': 10}, 'buyatsellatPPO': {'buyat': 1.1524, 'long': 28.6, 'sellat': 0.963, 'sellat_up': 1.0594, 'short': 15.959999999999999, 'signal': 13.750000000000002, 'stop_loss_pct': 0.9004, 'thresholds': {'down': -0.355, 'persistence': 3.12, 'up': 0.09}}, 'backtest': {'daterange': {'from': '2018-01-21 05:17:44', 'to': '2018-01-27 05:17:44'}}, 'performanceAnalyzer': {'riskFreeReturn': 2, 'enabled': True}, 'valid': True}, 'data': {'candleProps': ['id', 'start', 'open', 'high', 'low', 'close', 'vwp', 'volume', 'trades'], 'indicatorResults': True, 'report': True, 'roundtrips': False, 'trades': True}}
Error: config failure
http://localhost:3000/api/backtest
{'gekkoConfig': {'debug': True, 'info': True, 'watch': {'exchange': 'binance', 'currency': 'BTC', 'asset': 'ETH'}, 'paperTrader': {'fee': 0.25, 'feeMaker': 0.15, 'feeTaker': 0.25, 'feeUsing': 'maker', 'slippage': 0.05, 'simulationBalance': {'asset': 1, 'currency': 100}, 'reportRoundtrips': True, 'enabled': True}, 'tradingAdvisor': {'enabled': True, 'method': 'buyatsellatPPO', 'candleSize': 15, 'historySize': 10}, 'buyatsellatPPO': {'buyat': 1.0538, 'long': 29.64, 'sellat': 0.9440000000000001, 'sellat_up': 1.0195, 'short': 6.0, 'signal': 2.7, 'stop_loss_pct': 0.9188, 'thresholds': {'down': -0.48, 'persistence': 6.4, 'up': 0.105}}, 'backtest': {'daterange': {'from': '2018-01-21 05:17:44', 'to': '2018-01-27 05:17:44'}}, 'performanceAnalyzer': {'riskFreeReturn': 2, 'enabled': True}, 'valid': True}, 'data': {'candleProps': ['id', 'start', 'open', 'high', 'low', 'close', 'vwp', 'volume', 'trades'], 'indicatorResults': True, 'report': True, 'roundtrips': False, 'trades': True}}
Error: config failure
http://localhost:3000/api/backtest
{'gekkoConfig': {'debug': True, 'info': True, 'watch': {'exchange': 'binance', 'currency': 'BTC', 'asset': 'ETH'}, 'paperTrader': {'fee': 0.25, 'feeMaker': 0.15, 'feeTaker': 0.25, 'feeUsing': 'maker', 'slippage': 0.05, 'simulationBalance': {'asset': 1, 'currency': 100}, 'reportRoundtrips': True, 'enabled': True}, 'tradingAdvisor': {'enabled': True, 'method': 'buyatsellatPPO', 'candleSize': 15, 'historySize': 10}, 'buyatsellatPPO': {'buyat': 1.1949, 'long': 14.56, 'sellat': 0.9225, 'sellat_up': 1.0784, 'short': 14.64, 'signal': 9.16, 'stop_loss_pct': 0.9124, 'thresholds': {'down': -0.375, 'persistence': 8.0, 'up': 0.20500000000000002}}, 'backtest': {'daterange': {'from': '2018-01-21 05:17:44', 'to': '2018-01-27 05:17:44'}}, 'performanceAnalyzer': {'riskFreeReturn': 2, 'enabled': True}, 'valid': True}, 'data': {'candleProps': ['id', 'start', 'open', 'high', 'low', 'close', 'vwp', 'volume', 'trades'], 'indicatorResults': True, 'report': True, 'roundtrips': False, 'trades': True}}
Error: config failure
http://localhost:3000/api/backtest
{'gekkoConfig': {'debug': True, 'info': True, 'watch': {'exchange': 'binance', 'currency': 'BTC', 'asset': 'ETH'}, 'paperTrader': {'fee': 0.25, 'feeMaker': 0.15, 'feeTaker': 0.25, 'feeUsing': 'maker', 'slippage': 0.05, 'simulationBalance': {'asset': 1, 'currency': 100}, 'reportRoundtrips': True, 'enabled': True}, 'tradingAdvisor': {'enabled': True, 'method': 'buyatsellatPPO', 'candleSize': 15, 'historySize': 10}, 'buyatsellatPPO': {'buyat': 1.1541, 'long': 17.68, 'sellat': 0.9285, 'sellat_up': 1.1202, 'short': 13.44, 'signal': 6.95, 'stop_loss_pct': 0.9268, 'thresholds': {'down': -0.15999999999999998, 'persistence': 5.68, 'up': 0.495}}, 'backtest': {'daterange': {'from': '2018-01-21 05:17:44', 'to': '2018-01-27 05:17:44'}}, 'performanceAnalyzer': {'riskFreeReturn': 2, 'enabled': True}, 'valid': True}, 'data': {'candleProps': ['id', 'start', 'open', 'high', 'low', 'close', 'vwp', 'volume', 'trades'], 'indicatorResults': True, 'report': True, 'roundtrips': False, 'trades': True}}
Error: config failure
http://localhost:3000/api/backtest
{'gekkoConfig': {'debug': True, 'info': True, 'watch': {'exchange': 'binance', 'currency': 'BTC', 'asset': 'ETH'}, 'paperTrader': {'fee': 0.25, 'feeMaker': 0.15, 'feeTaker': 0.25, 'feeUsing': 'maker', 'slippage': 0.05, 'simulationBalance': {'asset': 1, 'currency': 100}, 'reportRoundtrips': True, 'enabled': True}, 'tradingAdvisor': {'enabled': True, 'method': 'buyatsellatPPO', 'candleSize': 15, 'historySize': 10}, 'buyatsellatPPO': {'buyat': 1.0861, 'long': 25.48, 'sellat': 0.9415, 'sellat_up': 1.1335, 'short': 12.24, 'signal': 16.47, 'stop_loss_pct': 0.9188, 'thresholds': {'down': -0.28500000000000003, 'persistence': 3.84, 'up': 0.3}}, 'backtest': {'daterange': {'from': '2018-01-21 05:17:44', 'to': '2018-01-27 05:17:44'}}, 'performanceAnalyzer': {'riskFreeReturn': 2, 'enabled': True}, 'valid': True}, 'data': {'candleProps': ['id', 'start', 'open', 'high', 'low', 'close', 'vwp', 'volume', 'trades'], 'indicatorResults': True, 'report': True, 'roundtrips': False, 'trades': True}}
Error: config failure
http://localhost:3000/api/backtest
{'gekkoConfig': {'debug': True, 'info': True, 'watch': {'exchange': 'binance', 'currency': 'BTC', 'asset': 'ETH'}, 'paperTrader': {'fee': 0.25, 'feeMaker': 0.15, 'feeTaker': 0.25, 'feeUsing': 'maker', 'slippage': 0.05, 'simulationBalance': {'asset': 1, 'currency': 100}, 'reportRoundtrips': True, 'enabled': True}, 'tradingAdvisor': {'enabled': True, 'method': 'buyatsellatPPO', 'candleSize': 15, 'historySize': 10}, 'buyatsellatPPO': {'buyat': 1.1881, 'long': 33.28, 'sellat': 0.9450000000000001, 'sellat_up': 1.0233, 'short': 13.08, 'signal': 4.91, 'stop_loss_pct': 0.9196, 'thresholds': {'down': -0.195, 'persistence': 7.04, 'up': 0.01}}, 'backtest': {'daterange': {'from': '2018-01-21 05:17:44', 'to': '2018-01-27 05:17:44'}}, 'performanceAnalyzer': {'riskFreeReturn': 2, 'enabled': True}, 'valid': True}, 'data': {'candleProps': ['id', 'start', 'open', 'high', 'low', 'close', 'vwp', 'volume', 'trades'], 'indicatorResults': True, 'report': True, 'roundtrips': False, 'trades': True}}
Error: config failure
http://localhost:3000/api/backtest
{'gekkoConfig': {'debug': True, 'info': True, 'watch': {'exchange': 'binance', 'currency': 'BTC', 'asset': 'ETH'}, 'paperTrader': {'fee': 0.25, 'feeMaker': 0.15, 'feeTaker': 0.25, 'feeUsing': 'maker', 'slippage': 0.05, 'simulationBalance': {'asset': 1, 'currency': 100}, 'reportRoundtrips': True, 'enabled': True}, 'tradingAdvisor': {'enabled': True, 'method': 'buyatsellatPPO', 'candleSize': 15, 'historySize': 10}, 'buyatsellatPPO': {'buyat': 1.1915, 'long': 16.9, 'sellat': 0.928, 'sellat_up': 1.048, 'short': 11.76, 'signal': 10.350000000000001, 'stop_loss_pct': 0.9027999999999999, 'thresholds': {'down': -0.28, 'persistence': 5.6, 'up': 0.145}}, 'backtest': {'daterange': {'from': '2018-01-21 05:17:44', 'to': '2018-01-27 05:17:44'}}, 'performanceAnalyzer': {'riskFreeReturn': 2, 'enabled': True}, 'valid': True}, 'data': {'candleProps': ['id', 'start', 'open', 'high', 'low', 'close', 'vwp', 'volume', 'trades'], 'indicatorResults': True, 'report': True, 'roundtrips': False, 'trades': True}}
Error: config failure
http://localhost:3000/api/backtest
{'gekkoConfig': {'debug': True, 'info': True, 'watch': {'exchange': 'binance', 'currency': 'BTC', 'asset': 'ETH'}, 'paperTrader': {'fee': 0.25, 'feeMaker': 0.15, 'feeTaker': 0.25, 'feeUsing': 'maker', 'slippage': 0.05, 'simulationBalance': {'asset': 1, 'currency': 100}, 'reportRoundtrips': True, 'enabled': True}, 'tradingAdvisor': {'enabled': True, 'method': 'buyatsellatPPO', 'candleSize': 15, 'historySize': 10}, 'buyatsellatPPO': {'buyat': 1.0334, 'long': 35.36, 'sellat': 0.922, 'sellat_up': 1.1677, 'short': 16.56, 'signal': 17.66, 'stop_loss_pct': 0.9219999999999999, 'thresholds': {'down': -0.305, 'persistence': 3.52, 'up': 0.105}}, 'backtest': {'daterange': {'from': '2018-01-21 05:17:44', 'to': '2018-01-27 05:17:44'}}, 'performanceAnalyzer': {'riskFreeReturn': 2, 'enabled': True}, 'valid': True}, 'data': {'candleProps': ['id', 'start', 'open', 'high', 'low', 'close', 'vwp', 'volume', 'trades'], 'indicatorResults': True, 'report': True, 'roundtrips': False, 'trades': True}}
Error: config failure
http://localhost:3000/api/backtest
{'gekkoConfig': {'debug': True, 'info': True, 'watch': {'exchange': 'binance', 'currency': 'BTC', 'asset': 'ETH'}, 'paperTrader': {'fee': 0.25, 'feeMaker': 0.15, 'feeTaker': 0.25, 'feeUsing': 'maker', 'slippage': 0.05, 'simulationBalance': {'asset': 1, 'currency': 100}, 'reportRoundtrips': True, 'enabled': True}, 'tradingAdvisor': {'enabled': True, 'method': 'buyatsellatPPO', 'candleSize': 15, 'historySize': 10}, 'buyatsellatPPO': {'buyat': 1.0589, 'long': 37.44, 'sellat': 0.9465, 'sellat_up': 1.1905, 'short': 13.08, 'signal': 8.48, 'stop_loss_pct': 0.8932, 'thresholds': {'down': -0.33499999999999996, 'persistence': 2.24, 'up': 0.24}}, 'backtest': {'daterange': {'from': '2018-01-21 05:17:44', 'to': '2018-01-27 05:17:44'}}, 'performanceAnalyzer': {'riskFreeReturn': 2, 'enabled': True}, 'valid': True}, 'data': {'candleProps': ['id', 'start', 'open', 'high', 'low', 'close', 'vwp', 'volume', 'trades'], 'indicatorResults': True, 'report': True, 'roundtrips': False, 'trades': True}}
Error: config failure
http://localhost:3000/api/backtest
{'gekkoConfig': {'debug': True, 'info': True, 'watch': {'exchange': 'binance', 'currency': 'BTC', 'asset': 'ETH'}, 'paperTrader': {'fee': 0.25, 'feeMaker': 0.15, 'feeTaker': 0.25, 'feeUsing': 'maker', 'slippage': 0.05, 'simulationBalance': {'asset': 1, 'currency': 100}, 'reportRoundtrips': True, 'enabled': True}, 'tradingAdvisor': {'enabled': True, 'method': 'buyatsellatPPO', 'candleSize': 15, 'historySize': 10}, 'buyatsellatPPO': {'buyat': 1.1744999999999999, 'long': 20.02, 'sellat': 0.931, 'sellat_up': 1.1449, 'short': 11.04, 'signal': 10.690000000000001, 'stop_loss_pct': 0.8956, 'thresholds': {'down': -0.10499999999999998, 'persistence': 3.2, 'up': 0.09}}, 'backtest': {'daterange': {'from': '2018-01-21 05:17:44', 'to': '2018-01-27 05:17:44'}}, 'performanceAnalyzer': {'riskFreeReturn': 2, 'enabled': True}, 'valid': True}, 'data': {'candleProps': ['id', 'start', 'open', 'high', 'low', 'close', 'vwp', 'volume', 'trades'], 'indicatorResults': True, 'report': True, 'roundtrips': False, 'trades': True}}
Error: config failure
http://localhost:3000/api/backtest
{'gekkoConfig': {'debug': True, 'info': True, 'watch': {'exchange': 'binance', 'currency': 'BTC', 'asset': 'ETH'}, 'paperTrader': {'fee': 0.25, 'feeMaker': 0.15, 'feeTaker': 0.25, 'feeUsing': 'maker', 'slippage': 0.05, 'simulationBalance': {'asset': 1, 'currency': 100}, 'reportRoundtrips': True, 'enabled': True}, 'tradingAdvisor': {'enabled': True, 'method': 'buyatsellatPPO', 'candleSize': 15, 'historySize': 10}, 'buyatsellatPPO': {'buyat': 1.1252, 'long': 18.72, 'sellat': 0.9585, 'sellat_up': 1.0537, 'short': 14.4, 'signal': 10.350000000000001, 'stop_loss_pct': 0.9212, 'thresholds': {'down': -0.295, 'persistence': 9.52, 'up': 0.34500000000000003}}, 'backtest': {'daterange': {'from': '2018-01-21 05:17:44', 'to': '2018-01-27 05:17:44'}}, 'performanceAnalyzer': {'riskFreeReturn': 2, 'enabled': True}, 'valid': True}, 'data': {'candleProps': ['id', 'start', 'open', 'high', 'low', 'close', 'vwp', 'volume', 'trades'], 'indicatorResults': True, 'report': True, 'roundtrips': False, 'trades': True}}
Error: config failure
http://localhost:3000/api/backtest
{'gekkoConfig': {'debug': True, 'info': True, 'watch': {'exchange': 'binance', 'currency': 'BTC', 'asset': 'ETH'}, 'paperTrader': {'fee': 0.25, 'feeMaker': 0.15, 'feeTaker': 0.25, 'feeUsing': 'maker', 'slippage': 0.05, 'simulationBalance': {'asset': 1, 'currency': 100}, 'reportRoundtrips': True, 'enabled': True}, 'tradingAdvisor': {'enabled': True, 'method': 'buyatsellatPPO', 'candleSize': 15, 'historySize': 10}, 'buyatsellatPPO': {'buyat': 1.1965999999999999, 'long': 14.56, 'sellat': 0.9265, 'sellat_up': 1.1335, 'short': 7.32, 'signal': 15.790000000000001, 'stop_loss_pct': 0.9219999999999999, 'thresholds': {'down': -0.44, 'persistence': 9.92, 'up': 0.28}}, 'backtest': {'daterange': {'from': '2018-01-21 05:17:44', 'to': '2018-01-27 05:17:44'}}, 'performanceAnalyzer': {'riskFreeReturn': 2, 'enabled': True}, 'valid': True}, 'data': {'candleProps': ['id', 'start', 'open', 'high', 'low', 'close', 'vwp', 'volume', 'trades'], 'indicatorResults': True, 'report': True, 'roundtrips': False, 'trades': True}}
Error: config failure
http://localhost:3000/api/backtest
{'gekkoConfig': {'debug': True, 'info': True, 'watch': {'exchange': 'binance', 'currency': 'BTC', 'asset': 'ETH'}, 'paperTrader': {'fee': 0.25, 'feeMaker': 0.15, 'feeTaker': 0.25, 'feeUsing': 'maker', 'slippage': 0.05, 'simulationBalance': {'asset': 1, 'currency': 100}, 'reportRoundtrips': True, 'enabled': True}, 'tradingAdvisor': {'enabled': True, 'method': 'buyatsellatPPO', 'candleSize': 15, 'historySize': 10}, 'buyatsellatPPO': {'buyat': 1.1065, 'long': 29.12, 'sellat': 0.933, 'sellat_up': 1.1088, 'short': 8.16, 'signal': 3.21, 'stop_loss_pct': 0.9308, 'thresholds': {'down': -0.185, 'persistence': 7.36, 'up': 0.0}}, 'backtest': {'daterange': {'from': '2018-01-21 05:17:44', 'to': '2018-01-27 05:17:44'}}, 'performanceAnalyzer': {'riskFreeReturn': 2, 'enabled': True}, 'valid': True}, 'data': {'candleProps': ['id', 'start', 'open', 'high', 'low', 'close', 'vwp', 'volume', 'trades'], 'indicatorResults': True, 'report': True, 'roundtrips': False, 'trades': True}}
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/root/gekko/japonicus/evolution_generations.py", line 39, in bEvaluate
    DateRange, phenotype, gekkoUrl)
  File "/root/gekko/japonicus/promoterz/evaluation/gekko.py", line 265, in Evaluate
    Debug=genconf.gekkoDebug) for DR in DateRange ]
  File "/root/gekko/japonicus/promoterz/evaluation/gekko.py", line 265, in <listcomp>
    Debug=genconf.gekkoDebug) for DR in DateRange ]
  File "/root/gekko/japonicus/promoterz/evaluation/gekko.py", line 108, in runBacktest
    result = httpPost(url, gekko_config)
  File "/root/gekko/japonicus/promoterz/evaluation/gekko.py", line 39, in httpPost
    raise e
  File "/root/gekko/japonicus/promoterz/evaluation/gekko.py", line 31, in httpPost
    Response = json.loads(Request.text)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "japonicus.py", line 99, in <module>
    gekko_generations(TargetParameters, GenerationMethod, EvaluationMode, web=APP)
  File "/root/gekko/japonicus/evolution_generations.py", line 106, in gekko_generations
    World.runEPOCH()
  File "/root/gekko/japonicus/promoterz/sequence/parallel_world.py", line 12, in world_EPOCH
    LOCALE.run()
  File "/root/gekko/japonicus/promoterz/locale.py", line 51, in run
    self.loop(self.World, self)
  File "/root/gekko/japonicus/promoterz/sequence/standard_loop.py", line 34, in standard_loop
    locale.extraStats['nb_evaluated'], locale.extraStats['avgTrades'] = World.parallel.evaluatePopulation(locale)
  File "/root/gekko/japonicus/promoterz/evaluationPool.py", line 64, in evaluatePopulation
    results[A] = results[A].get(timeout=timeout)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/root/gekko/japonicus/promoterz/evaluationPool.py", line 35, in evaluateBackend
    fitnesses = P.starmap(self.EvaluationTool, Q )
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 274, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by Gab0** [comment]
Do you have the strategy file for this strat on `strategies` folder of gekko? Its the following file:

buyatsellatPPO.js
```
// helpers
// var _ = require('lodash');
var log = require('../core/log.js');

//var config = require('../core/util.js').getConfig();
//var settings = config.buyatsellat;

// let's create our own method
var method = {};

// prepare everything our method needs
  method.init = function() {
  this.name = 'buyatsellat';

  this.previousAction = 'sell';
  this.previousActionPrice = Infinity;

  this.addIndicator('ppo', 'PPO', this.settings);
}

// What happens on every new candle?
method.update = function(candle) {
  //log.debug('in update');
}

// for debugging purposes log the last 
// calculated parameters.
method.log = function(candle) {
  //log.debug(this.previousAction)
}

method.check = function(candle) {  

  PPO = this.indicators.ppo.PPOhist;
  if(this.previousAction === "buy") {
    // calculate the minimum price in order to sell
    const threshold = this.previousActionPrice * this.settings.buyat;

    // calculate the stop loss price in order to sell
    const stop_loss = this.previousActionPrice * this.settings.stop_loss_pct;

    // we sell if the price is more than the required threshold or equals stop loss threshold
    var sellCondition = (candle.close > threshold) || (candle.close < stop_loss);

    if(sellCondition || PPO <= this.settings.thresholds.down) {
      this.advice('short');
      this.previousAction = 'sell';
      this.previousActionPrice = candle.close;
    }
  }

  else if(this.previousAction === "sell") {
  // calculate the minimum price in order to buy
    const threshold = this.previousActionPrice * this.settings.sellat;

  // calculate the price at which we should buy again if market goes up
    const sellat_up_price = this.previousActionPrice * this.settings.sellat_up;

    var buyCondition = (candle.close < threshold) || (candle.close > sellat_up_price);
    // we buy if the price is less than the required threshold or greater than Market Up threshold
    if(buyCondition || PPO >= this.settings.thresholds.up) {
      this.advice('long');
      this.previousAction = 'buy';
      this.previousActionPrice = candle.close;
    }
  }
}

module.exports = method;
```

**Comment by deadheadtn** [comment]
fixed when i changed the name from buyatsellat to buyatsellat_ui in the `configStrategies.py` file 
thank you

**Comment by CryptoCoeus** [comment]
Hi @deadheadtn, does that start work for you ? Have you tried on live ?

**Comment by deadheadtn** [comment]
@CryptoCoeus the is always a % of difference between what you backtested and what you get on live trading, you have to take into consideration the candlesize (work on bigger candlesize to eliminate the noise), also don't try to over tweak your parameters
