### ISSUE TITLE
Cannot import name supplement

### ISSUE THREAD

**Issue by shuruheel** [Gab0/japonicus#67]
python japonicus.py -b --strat PPO  --repeat 100 -w

Traceback (most recent call last):
  File "japonicus.py", line 9, in <module>
    from evolution_generations import gekko_generations
  File "/root/gekko/japonicus/evolution_generations.py", line 4, in <module>
    import promoterz
  File "/root/gekko/japonicus/promoterz/__init__.py", line 5, in <module>
    from . import supplement, validation, utils
ImportError: cannot import name supplement

**Comment by coltac** [comment]
python3 japonicus.py -b --strat PPO --repeat 100 -w

**Comment by shuruheel** [comment]
That worked. Thanks!
