### ISSUE TITLE
Help with running Multi-Strategy results

### ISSUE THREAD

**Issue by BradT7** [Gab0/japonicus#71]
So I was able to run my first GA using your PPOTSI strategy, and got the results of that ready to go.
The issue I'm having now is how to go about entering them properly in the gekko ui page.
I've tried copy and pasting as given in japonicus results, and tried tweaking the code layout in the ui and the config file, but keep getting errors in the gekko terminal, likely do to incorrect formatting. 

Could anyone provide a sample config and ui code for defining multiple variables across multiple strategies? I suppose this would all get tucked under the config.PPOTSI strategy code in the config file in addition to the web ui settings box.  Let me know if you'd like to see any error snapshots or the code I'm using now.

If I can figure this out, then I can hopefully figure out future pairings on my own, and maybe even write my own strategies.js file to match, by comparing PPOTSI strategy code to the default PPO and TSI and see how they were blended in the code, and then teach myself how to add another pairing, or maybe even Supertrend strategy paired with something else.  Thanks!

**Comment by BradT7** [comment]
This is what I get when pasting the completed GA test results for PPOTSI
 -- Settings for Gekko --ui webpage -- 
```
persistence = 7.48
[PPO]
down = -0.16
long = 22.12
short = 5.86
signal = 17.4
up = 0.6

[TSI]
down = -14.8
long = 11.28
short = 17.25
up = 19.3
```

```
  <-- POST /api/backtest
2018-02-03 19:36:53 (INFO):	Setting up Gekko in backtest mode
2018-02-03 19:36:53 (INFO):	
2018-02-03 19:36:53 (INFO):	Setting up:
2018-02-03 19:36:53 (INFO):		 Trading Advisor
2018-02-03 19:36:53 (INFO):		 Calculate trading advice
2018-02-03 19:36:53 (INFO):		 Using the strategy: PPOTSI
2018-02-03 19:36:53 (WARN):	TULIP indicators could not be loaded, they will be unavailable.
/home/brad/gekko/strategies/indicators/TSI.js:8
  this.inner = new EMA(settings.long);
                                ^

TypeError: Cannot read property 'long' of undefined
    at new Indicator (/home/brad/gekko/strategies/indicators/TSI.js:8:33)
    at Base.addIndicator (/home/brad/gekko/plugins/tradingAdvisor/baseTradingMethod.js:294:27)
    at Base.bound [as addIndicator] (/home/brad/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Base.method.init (/home/brad/gekko/strategies/PPOTSI.js:22:8)
    at Base.bound [as init] (/home/brad/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at new Base (/home/brad/gekko/plugins/tradingAdvisor/baseTradingMethod.js:84:8)
    at Actor.setupTradingMethod (/home/brad/gekko/plugins/tradingAdvisor/tradingAdvisor.js:62:17)
    at Actor.bound [as setupTradingMethod] (/home/brad/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at new Actor (/home/brad/gekko/plugins/tradingAdvisor/tradingAdvisor.js:23:8)
    at load (/home/brad/gekko/core/pluginUtil.js:95:22)
  xxx POST /api/backtest 500 179ms -

  Error: non-error thrown: Child process has died.
      at Object.onerror (/home/brad/gekko/node_modules/koa/lib/context.js:105:40)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:160:7)
```
