### ISSUE TITLE
cannot import name supplement

### ISSUE THREAD

**Issue by thak777** [Gab0/japonicus#77]
After following all of the installation steps, I try to run the script and I get an error about not being able to import supplement.  Not exactly sure what's going on, as I assume that's a standard library.

What am I missing?

> thak@DESKTOP-3SPPG79:~/japonicus$ python japonicus.py -b --strat Supertrend -w
> Traceback (most recent call last):
>   File "japonicus.py", line 8, in <module>
>     from evolution_generations import gekko_generations
>   File "/home/thak/japonicus/evolution_generations.py", line 4, in <module>
>     import promoterz
>   File "/home/thak/japonicus/promoterz/__init__.py", line 5, in <module>
>     from . import supplement, validation, utils
> ImportError: cannot import name supplement

**Comment by thak777** [comment]
Wow.  I guess the key was to run python3 instead of python.

I also had to manually add a few packages (like python3-tk), but it runs now.

(On Ubuntu on Windows 10, for anyone else looking at this later.)
