### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by shuruheel** [Gab0/japonicus#80]
I'm trying to run japonicus with a custom strategy involving the RSI and BBands indicators (Tulip) but while it works in the Gekko UI, I get the following error when trying to run it with japonicus: 

Traceback (most recent call last):
  File "japonicus.py", line 100, in <module>
    gekko_generations(TargetParameters, GenerationMethod, EvaluationMode, web=APP)
  File "/root/gekko/japonicus/evolution_generations.py", line 106, in gekko_generations
    World.runEPOCH()
  File "/root/gekko/japonicus/promoterz/sequence/parallel_world.py", line 12, in world_EPOCH
    LOCALE.run()
  File "/root/gekko/japonicus/promoterz/locale.py", line 51, in run
    self.loop(self.World, self)
  File "/root/gekko/japonicus/promoterz/sequence/standard_loop.py", line 34, in standard_loop
    locale.extraStats['nb_evaluated'], locale.extraStats['avgTrades'] = World.parallel.evaluatePopulation(locale)
  File "/root/gekko/japonicus/promoterz/evaluationPool.py", line 64, in evaluatePopulation
    results[A] = results[A].get(timeout=timeout)
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/root/gekko/japonicus/promoterz/evaluationPool.py", line 35, in evaluateBackend
    fitnesses = P.starmap(self.EvaluationTool, Q )
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 268, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Error: config failure
http://localhost:3000/api/backtest
{'gekkoConfig': {'paperTrader': {'feeTaker': 0.25, 'reportRoundtrips': True, 'feeMaker': 0.15, 'fee': 0.25, 'simulationBalance': {'asset': 1, 'currency': 100}, 'slippage': 0.05, 'enabled': True, 'feeUsing': 'maker'}, 'backtest': {'daterange': {'to': '2017-10-28 08:42:20', 'from': '2017-10-07 08:42:20'}}, 'valid': True, 'watch': {'exchange': 'kraken', 'asset': 'ETH', 'currency': 'EUR'}, 'tradingAdvisor': {'historySize': 10, 'method': 'rsi_bbands', 'candleSize': 5, 'enabled': True}, 'debug': True, 'rsi_bbands': {'rsi_high': 88.8, 'optInNbStdDevs': 1.8399999999999999, 'rsi_low': 17.6, 'stop_loss': -0.0975, 'optInTimePeriod': 15.639999999999999, 'min_hold': 5.4399999999999995, 'swing_trade': 0.0}, 'info': True, 'performanceAnalyzer': {'riskFreeReturn': 2, 'enabled': True}}, 'data': {'roundtrips': False, 'report': True, 'indicatorResults': True, 'candleProps': ['id', 'start', 'open', 'high', 'low', 'close', 'vwp', 'volume', 'trades'], 'trades': True}}
Error: config failure

Any clues??

**Comment by Gab0** [comment]
It says config failure, and with all the magic that happens sometimes on computer programs lol in this case it seems to be not misleading.
From the debug it seems perfect, plz check your strat for settings errors, you can even post it here,.
