### ISSUE TITLE
Connection Error on Limited CPU Resources

### ISSUE THREAD

**Issue by BradT7** [Gab0/japonicus#90]
Hello, this is more of an FYI.  I've just been running some back tests on an older 2x Xeon E5-2660 (32 core) server, and found I got the following error when running a CPU miner at 80% CPU.  I know this isn't really an expected environment, but got me thinking I should still let you know, because perhaps this could be an issue on slower CPU's in general.  Perhaps there could be some improvements in the code efficiency when there are conflicting processes fighting for CPU power and therefore causing japonicus (or perhaps gekko) to fail.  Maybe a fail safe catch could be implemented to try again if there is a failure to conflicting CPU resources.  This happened even when setting the parallels as low as 8.
As soon as I turned off the miner I've had a successful 800 epochs with 24 parallels.
Here is the code for your review. 

```
Error: config failure
http://localhost:3000/api/backtest
{'gekkoConfig': {'debug': True, 'info': True, 'watch': {'exchange': 'binance', 'currency': 'USDT', 'asset': 'BTC'}, 'paperTrader': {'fee': 0.25, 'feeMaker': 0.15, 'feeTaker': 0.25, 'feeUsing': 'maker', 'slippage': 0.05, 'simulationBalance': {'asset': 1, 'currency': 100}, 'reportRoundtrips': True, 'enabled': True}, 'tradingAdvisor': {'enabled': True, 'method': 'RSI_BULL_BEAR', 'candleSize': 5, 'historySize': 10}, 'RSI_BULL_BEAR': {'BEAR_RSI': 17.5, 'BEAR_RSI_high': 32.0, 'BEAR_RSI_low': 12.0, 'BULL_RSI': 14.200000000000001, 'BULL_RSI_high': 85.4, 'BULL_RSI_low': 52.0, 'SMA_long': 605.0, 'SMA_short': 46.0}, 'backtest': {'daterange': {'from': '2017-11-01 00:00:00', 'to': '2018-02-23 18:58:00'}}, 'performanceAnalyzer': {'riskFreeReturn': 2, 'enabled': True}, 'valid': True}, 'data': {'candleProps': ['id', 'start', 'open', 'high', 'low', 'close', 'vwp', 'volume', 'trades'], 'indicatorResults': True, 'report': True, 'roundtrips': False, 'trades': True}}
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/dist-packages/requests/packages/urllib3/connectionpool.py", line 386, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.6/dist-packages/requests/packages/urllib3/connectionpool.py", line 382, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 438, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/dist-packages/requests/packages/urllib3/connectionpool.py", line 649, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.6/dist-packages/requests/packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.6/dist-packages/requests/packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/dist-packages/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/dist-packages/requests/packages/urllib3/connectionpool.py", line 386, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.6/dist-packages/requests/packages/urllib3/connectionpool.py", line 382, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/brad/gekko/japonicus/evolution_generations.py", line 45, in bEvaluate
    DateRange, phenotype, gekkoUrl)
  File "/home/brad/gekko/japonicus/promoterz/evaluation/gekko.py", line 269, in Evaluate
    Debug=genconf.gekkoDebug) for DR in DateRange ]
  File "/home/brad/gekko/japonicus/promoterz/evaluation/gekko.py", line 269, in <listcomp>
    Debug=genconf.gekkoDebug) for DR in DateRange ]
  File "/home/brad/gekko/japonicus/promoterz/evaluation/gekko.py", line 112, in runBacktest
    result = httpPost(url, gekko_config)
  File "/home/brad/gekko/japonicus/promoterz/evaluation/gekko.py", line 39, in httpPost
    raise e
  File "/home/brad/gekko/japonicus/promoterz/evaluation/gekko.py", line 30, in httpPost
    Request = requests.post(URL, json=data)
  File "/usr/local/lib/python3.6/dist-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 518, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 639, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 488, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "japonicus.py", line 111, in <module>
    gekko_generations(TargetParameters, GenerationMethod, EvaluationMode, web=APP)
  File "/home/brad/gekko/japonicus/evolution_generations.py", line 131, in gekko_generations
    resultInterface.showResults(World)
  File "/home/brad/gekko/japonicus/resultInterface.py", line 66, in showResults
    [ [evaluationDaterange]] , 0, [FinalIndividue])
  File "/home/brad/gekko/japonicus/promoterz/evaluationPool.py", line 36, in evaluateBackend
    fitnesses = P.starmap(self.EvaluationTool, Q )
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 274, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
```

**Comment by Gab0** [comment]
Thanks for that report. 
I'm no expert on CPU resource tuning on python async parallel mapping but will see what is possible to do.
