### ISSUE TITLE
Error: config failure

### ISSUE THREAD

**Issue by elmolinger** [Gab0/japonicus#93]
I ran Japonicus overnight and got this error.

Maybe timeout?

```
Locale12
first unevaluated: 13
7 individues removed due to equality
[6]
EPOCH 59        &6
Maximum profit 43.902   Average profit 5.969
Minimum profit -250.911 Profit variation 85.986
Population size 28      Max population size 29
Avg trade number 75     Avg sharpe ratio 0.228

Elder dies 0

Locale13
first unevaluated: 10
1 individues removed due to equality
[9]
Error: config failure
http://localhost:3000/api/backtest
{'gekkoConfig': {'debug': True, 'info': True, 'watch': {'exchange': 'bitfinex', 'currency': 'USD', 'asset': 'LTC'}, 'paperTrader': {'fee': 0.25, 'feeMaker': 0.15, 'feeTaker': 0.25, 'feeUsing': 'maker', 'slippage': 0.05, 'simulationBalance': {'asset': 1, 'currency': 100}, 'reportRoundtrips': True, 'enabled': True}, 'tradingAdvisor': {'enabled': True, 'method': 'RSI_BULL_BEAR_ADX', 'candleSize': 15, 'historySize': 10}, 'RSI_BULL_BEAR_ADX': {'ADX': 2.95, 'ADX_high': 67.9, 'ADX_low': 47.6, 'BEAR_RSI': 12.620000000000001, 'BEAR_RSI_high': 72.5, 'BEAR_RSI_low': 38.2, 'BULL_RSI': 11.83, 'BULL_RSI_high': 75.88, 'BULL_RSI_low': 44.6, 'SMA_long': 918.0, 'SMA_short': 48.8}, 'backtest': {'daterange': {'from': '2017-07-18 02:09:34', 'to': '2017-09-16 02:09:34'}}, 'performanceAnalyzer': {'riskFreeReturn': 2, 'enabled': True}, 'valid': True}, 'data': {'candleProps': ['id', 'start', 'open', 'high', 'low', 'close', 'vwp', 'volume', 'trades'], 'indicatorResults': True, 'report': True, 'roundtrips': False, 'trades': True}}
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/dist-packages/requests/packages/urllib3/connectionpool.py", line 386, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.6/dist-packages/requests/packages/urllib3/connectionpool.py", line 382, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 438, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/dist-packages/requests/packages/urllib3/connectionpool.py", line 649, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.6/dist-packages/requests/packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.6/dist-packages/requests/packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/dist-packages/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/dist-packages/requests/packages/urllib3/connectionpool.py", line 386, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.6/dist-packages/requests/packages/urllib3/connectionpool.py", line 382, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/elmolinger/gekko/japonicus/evolution_generations.py", line 46, in bEvaluate
    DateRange, phenotype, gekkoUrl)
  File "/home/elmolinger/gekko/japonicus/promoterz/evaluation/gekko.py", line 269, in Evaluate
    Debug=genconf.gekkoDebug) for DR in DateRange ]
  File "/home/elmolinger/gekko/japonicus/promoterz/evaluation/gekko.py", line 269, in <listcomp>
    Debug=genconf.gekkoDebug) for DR in DateRange ]
  File "/home/elmolinger/gekko/japonicus/promoterz/evaluation/gekko.py", line 112, in runBacktest
    result = httpPost(url, gekko_config)
  File "/home/elmolinger/gekko/japonicus/promoterz/evaluation/gekko.py", line 39, in httpPost
    raise e
  File "/home/elmolinger/gekko/japonicus/promoterz/evaluation/gekko.py", line 30, in httpPost
    Request = requests.post(URL, json=data)
  File "/usr/local/lib/python3.6/dist-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 518, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 639, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 488, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "japonicus.py", line 111, in <module>
    gekko_generations(TargetParameters, GenerationMethod, EvaluationMode, web=APP)
  File "/home/elmolinger/gekko/japonicus/evolution_generations.py", line 131, in gekko_generations
    World.runEPOCH()
  File "/home/elmolinger/gekko/japonicus/promoterz/sequence/parallel_world.py", line 12, in world_EPOCH
    LOCALE.run()
  File "/home/elmolinger/gekko/japonicus/promoterz/locale.py", line 54, in run
    self.loop(self.World, self)
  File "/home/elmolinger/gekko/japonicus/promoterz/sequence/standard_loop.py", line 34, in standard_loop
    locale.extraStats['nb_evaluated'], locale.extraStats['avgTrades'] = World.parallel.evaluatePopulation(locale)
  File "/home/elmolinger/gekko/japonicus/promoterz/evaluationPool.py", line 69, in evaluatePopulation
    results[A] = results[A].get(timeout=timeout)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/elmolinger/gekko/japonicus/promoterz/evaluationPool.py", line 36, in evaluateBackend
    fitnesses = P.starmap(self.EvaluationTool, Q )
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 274, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))```

**Comment by dano000** [comment]
I have a similar bug

**Comment by Gab0** [comment]
@dano000, @elmolinger Yeah thats a timeout. Can one of you guys provide info on settings and strategy used? Also, about your rig and usage context? Thanks.

**Comment by dano000** [comment]
I was using:
AWS Micro instance, Ubuntu 16.04 - using the command: `python3.6 japonicus.py -g -c --strat RSI`
Settings were default, except delta window was 1 day instead of 60.

**Comment by Gab0** [comment]
Oh I see. AWS Micro has a credit system, where the machine runs fine while it has credits, then they are over and CPU performance is severely handicapped. That can explain the timeout :/ AWS micro are no good. cheers!
